sudo: required
services:
  - docker

before_install:
  - docker build -f -t alexandre1984rj/docker-react Dockerfile.dev .

script:
  - docker run -e CI=true alexandre1984rj/docker-react npm run test -- --coverage
